/* This creates the database, that stores all the data of the application */
CREATE DATABASE photoapp;

/*This is to use the photoapp database*/
USE photoapp;


/*Creates the user table, with 3 columns */
DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
	MAIL_ID VARCHAR(320), 
	USER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(20), 
	LAST_NAME VARCHAR(20)
);

/*Creates the post table, which holds all the information about the post*/
DROP TABLE IF EXISTS POST;
CREATE TABLE POST
(
	POST_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	MAIL_ID VARCHAR(320), 
	USER_ID INTEGER,
	TOPIC_ID INTEGER, 
	URL VARCHAR(100), 
	DESCRIPTION VARCHAR(100),
	UPLOADTIME DATETIME,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

/*Creates the votes table*/
DROP TABLE IF EXISTS VOTES;
CREATE TABLE VOTES
(
	POST_ID INTEGER AUTO_INCREMENT,
	VOTECOUNT INTEGER DEFAULT 0,
	FOREIGN KEY(POST_ID) REFERENCES POST(POST_ID)
);

/*Creates the 'topic' table*/
DROP TABLE IF EXISTS TOPIC;
CREATE TABLE TOPIC
(
	TOPIC_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MAIL_ID VARCHAR(320),
	TITLE VARCHAR(50),
	IS_CURRENT BOOLEAN DEFAULT 0,
	VOTER_MAILID
);

/* This query creates the table comments*/
DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS
(
	POST_ID INTEGER AUTO_INCREMENT,
	COMMENTID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	MAIL_ID VARCHAR(320), 
	CONTENT VARCHAR(100),
	FOREIGN KEY(POST_ID) REFERENCES POST(POST_ID)
);

