
/*This is to use the photoapp database*/
USE 'photoapp';

DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS VOTES;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS TOPIC;
DROP TABLE IF EXISTS USER;


/*Creates the user table, with 3 columns */
CREATE TABLE USER
(
	USER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MAIL_ID VARCHAR(254) UNIQUE, 
	FIRST_NAME VARCHAR(20), 
	LAST_NAME VARCHAR(20),
	NO_OF_POSTS INTEGER DEFAULT 0, 
	IS_ACTIVE BOOLEAN DEFAULT 1
);


/*Creates the topic table*/
CREATE TABLE TOPIC
(
	TOPIC_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID INTEGER,
	TOPIC_TITLE VARCHAR(100),
	IS_ACTIVE BOOLEAN DEFAULT 1,
	IS_CURRENT BOOLEAN DEFAULT 1,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);


/*Creates the post table, which holds all the information about the post.*/
CREATE TABLE POST
(
	POST_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	USER_ID INTEGER,
	TOPIC_ID INTEGER, 
	URL VARCHAR(100), 
	DESCRIPTION VARCHAR(100),
	UPLOAD_TIME TIMESTAMP,
	IS_ACTIVE BOOLEAN DEFAULT 1,
	NEXT_TOPIC VARCHAR(100),
	FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC(TOPIC_ID),
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);


/*Creates the votes table*/
CREATE TABLE VOTES
(
	VOTE_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	POST_ID INTEGER,
	USER_ID INTEGER,
	IS_ACTIVE BOOLEAN DEFAULT 1,
	VOTED_TIME TIMESTAMP,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
	FOREIGN KEY(POST_ID) REFERENCES POST(POST_ID)
);


/* This query creates the table comments*/
CREATE TABLE COMMENTS
(
	COMMENT_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	POST_ID INTEGER,
	USER_ID INTEGER,
	COMMENT_CONTENT VARCHAR(100),
	IS_ACTIVE BOOLEAN DEFAULT 1,
	UPLOAD_TIME TIMESTAMP,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
	FOREIGN KEY(POST_ID) REFERENCES POST(POST_ID)
);


