DROP PROCEDURE IF EXISTS ADD_VOTE;
/* This stored procedure when executed, adds a vote for a particular post */
DELIMITER //
CREATE PROCEDURE ADD_VOTE
(
	IN _POST_ID INTEGER,
	IN _USER_ID INTEGER,
	OUT _VOTE_ID INTEGER
)
BEGIN
	INSERT INTO VOTES(POST_ID, USER_ID) VALUES(_POST_ID, _USER_ID);
	
	SELECT V.VOTE_ID FROM VOTES V WHERE V.USER_ID = _USER_ID;
END;
//
DELIMITER ;


DROP PROCEDURE IF EXISTS UPDATE_VOTE;
/* This stored procedure when executed, Displays the recently casted votes for a particular post */
DELIMITER //
CREATE PROCEDURE UPDATE_VOTE
(
	IN _VOTE_ID INTEGER,
	IN _POST_ID INTEGER, 
	IN _USER_ID INTEGER
)
BEGIN
	SELECT V.IS_ACTIVE FROM VOTES V WHERE V.VOTE_ID = VOTE_ID; 
	IF V.IS_ACTIVE = 0 THEN
		UPDATE VOTES V
			SET V.IS_ACTIVE = 1
				WHERE V.VOTE_ID = _VOTE_ID;
	ELSE
		UPDATE VOTES V
			SET V.IS_ACTIVE = 0
				WHERE V.VOTE_ID = _VOTE_ID;
	END IF;
END;
//
DELIMITER ;
